# Generated by Django 5.2 on 2025-05-29 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=80)),
                ('birth_date', models.DateTimeField()),
                ('document', models.CharField(max_length=80)),
                ('data_complete', models.BooleanField(default=False)),
                ('qa_average', models.FloatField()),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_module.establishment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
