# Generated by Django 5.2 on 2025-07-15 20:35

from django.db import migrations
import datetime
from django.contrib.auth.hashers import make_password

def create_initial_users(apps, schema_editor):
    User = apps.get_model('auth','User')
    Profile = apps.get_model('login_module', 'Profile')
    Group = apps.get_model('auth', 'Group')



    # Obtener o crear el grupo de administradores
    admin_group, _ = Group.objects.get_or_create(name='Administrador')


    #Usuario 1
    admin1, created1 = User.objects.get_or_create(
        username='admin1',
        defaults={
            'email': 'admin1@example.com',
        }
    )

    if created1:
        admin1.password = make_password('admin1234')
        admin1.save()
    admin1.groups.add(admin_group)

    # Crear perfil 1
    Profile.objects.get_or_create(
        user=admin1,
        defaults={
            'phone': 1234567890,
            'address': 'Dirección admin1',
            'birth_date': datetime.date(1990, 1, 1),
            'document': '12345111',
            'data_complete': True,
            'establishment': None,
            'qa_average': 5.0,
        }
    )

    # Crear usuario 2
    admin2, created2 = User.objects.get_or_create(
        username='admin2',
        defaults={
            'email': 'admin2@example.com',
        }
    )
    if created2:
        admin2.password = make_password('admin1234')
        admin2.save()

    # Crear perfil 2
    Profile.objects.get_or_create(
        user=admin2,
        defaults={
            'phone': 9876543210,
            'address': 'Dirección admin2',
            'birth_date': datetime.date(1992, 2, 2),
            'document': '6789022',
            'data_complete': True,
            'establishment': None,
            'qa_average': 5.0,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
        ('core','0001_create_initial_groups')
    ]

    operations = [
        migrations.RunPython(create_initial_users),
    ]
