# Generated by Django 5.2 on 2025-10-17 21:31

from django.db import migrations
import datetime
from django.contrib.auth.hashers import make_password


def create_initial_users(apps, schema_editor):
    """
    Crea usuarios administradores iniciales para gestionar los establecimientos.
    Credenciales:
    - Usuario: admin1 / Contraseña: admin1234
    - Usuario: admin2 / Contraseña: admin1234
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('login_module', 'Profile')
    Group = apps.get_model('auth', 'Group')

    # Obtener el grupo de administradores
    admin_group = Group.objects.get(name='Administrador')

    # Usuario administrador 1
    admin1, created1 = User.objects.get_or_create(
        username='admin1',
        defaults={
            'email': 'admin1@barberb.com',
            'first_name': 'Carlos',
            'last_name': 'Administrador',
            'is_staff': True,
            'is_superuser': False,
        }
    )

    if created1:
        admin1.password = make_password('admin1234')
        admin1.save()
    
    admin1.groups.add(admin_group)

    # Crear perfil para admin1
    Profile.objects.get_or_create(
        user=admin1,
        defaults={
            'phone': 3001234567,
            'address': 'Calle Kennedy 100 #12-34',
            'birth_date': datetime.date(1985, 5, 15),
            'document': '1234567890',
            'data_complete': True,
            'establishment': None,
            'qa_average': 5.0,
        }
    )

    # Usuario administrador 2
    admin2, created2 = User.objects.get_or_create(
        username='admin2',
        defaults={
            'email': 'admin2@barberb.com',
            'first_name': 'María',
            'last_name': 'Administradora',
            'is_staff': True,
            'is_superuser': False,
        }
    )
    
    if created2:
        admin2.password = make_password('admin1234')
        admin2.save()
    
    admin2.groups.add(admin_group)

    # Crear perfil para admin2
    Profile.objects.get_or_create(
        user=admin2,
        defaults={
            'phone': 3009876543,
            'address': 'Carrera Timiza 50 #22-11',
            'birth_date': datetime.date(1988, 8, 20),
            'document': '9876543210',
            'data_complete': True,
            'establishment': None,
            'qa_average': 5.0,
        }
    )


def reverse_users(apps, schema_editor):
    """Elimina los usuarios creados si se revierte la migración"""
    User = apps.get_model('auth', 'User')
    User.objects.filter(username__in=['admin1', 'admin2']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
        ('core', '0001_create_initial_groups'),
    ]

    operations = [
        migrations.RunPython(create_initial_users, reverse_users),
    ]
