# Generated by Django 5.2.4 on 2025-07-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
