# Generated by Django 5.2 on 2025-10-17 21:33

from django.db import migrations
import datetime
from django.contrib.auth.hashers import make_password


def create_barbers_and_clients(apps, schema_editor):
    """
    Crea barberos y clientes de prueba para cada establecimiento.
    
    Barberos (contraseña: barbero1234):
    - josequintero (Kennedy)
    - danielperez (Kennedy)
    - marcogomez (Timiza)
    - andreslopez (Timiza)
    
    Cliente (contraseña: cliente1234):
    - lauratorres
    """
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Profile = apps.get_model('login_module', 'Profile')
    Establishment = apps.get_model('establishment', 'Establishment')

    # Obtener grupos
    barbero_group = Group.objects.get(name='Barbero')
    cliente_group = Group.objects.get(name='Cliente')

    # Obtener establecimientos
    try:
        est_kennedy = Establishment.objects.get(name_est='BarberShop Kennedy')
        est_timiza = Establishment.objects.get(name_est='BarberShop Timiza')
    except Establishment.DoesNotExist:
        return  # Si no existen los establecimientos, abortar

    # Barberos para Kennedy
    barberos_kennedy = [
        {
            'username': 'josequintero',
            'first_name': 'José',
            'last_name': 'Quintero',
            'email': 'jquintero@barberb.com',
            'phone': 3011234567,
            'address': 'Calle 45 #12-34',
            'birth_date': datetime.date(1990, 6, 15),
            'document': '1012345678',
        },
        {
            'username': 'danielperez',
            'first_name': 'Daniel',
            'last_name': 'Pérez',
            'email': 'dperez@barberb.com',
            'phone': 3019876543,
            'address': 'Carrera 23 #56-78',
            'birth_date': datetime.date(1992, 9, 21),
            'document': '1087654321',
        },
    ]

    # Barberos para Timiza
    barberos_timiza = [
        {
            'username': 'marcogomez',
            'first_name': 'Marco',
            'last_name': 'Gómez',
            'email': 'mgomez@barberb.com',
            'phone': 3021234567,
            'address': 'Diagonal 10 #33-44',
            'birth_date': datetime.date(1988, 2, 10),
            'document': '1056789012',
        },
        {
            'username': 'andreslopez',
            'first_name': 'Andrés',
            'last_name': 'López',
            'email': 'alopez@barberb.com',
            'phone': 3029876543,
            'address': 'Transversal 8 #22-55',
            'birth_date': datetime.date(1993, 12, 5),
            'document': '1021098765',
        },
    ]

    # Función auxiliar para crear barberos
    def crear_barbero(data, establecimiento):
        user, created = User.objects.get_or_create(
            username=data['username'],
            defaults={
                'email': data['email'],
                'first_name': data['first_name'],
                'last_name': data['last_name'],
                'is_staff': True,
                'is_superuser': False,
            }
        )
        if created:
            user.password = make_password('barbero1234')
            user.save()
        
        user.groups.add(barbero_group)

        Profile.objects.get_or_create(
            user=user,
            defaults={
                'phone': data['phone'],
                'address': data['address'],
                'birth_date': data['birth_date'],
                'document': data['document'],
                'data_complete': True,
                'establishment': establecimiento,
                'qa_average': 4.5,
            }
        )

    # Crear barberos de Kennedy
    for barbero_data in barberos_kennedy:
        crear_barbero(barbero_data, est_kennedy)

    # Crear barberos de Timiza
    for barbero_data in barberos_timiza:
        crear_barbero(barbero_data, est_timiza)

    # Crear cliente de prueba
    cliente_user, created = User.objects.get_or_create(
        username='lauratorres',
        defaults={
            'email': 'ltorres@gmail.com',
            'first_name': 'Laura',
            'last_name': 'Torres',
            'is_staff': False,
            'is_superuser': False,
        }
    )
    
    if created:
        cliente_user.password = make_password('cliente1234')
        cliente_user.save()
    
    cliente_user.groups.add(cliente_group)

    Profile.objects.get_or_create(
        user=cliente_user,
        defaults={
            'phone': 3105556677,
            'address': 'Calle 100 #20-10',
            'birth_date': datetime.date(1995, 4, 18),
            'document': '1011223344',
            'data_complete': True,
            'establishment': None,
            'qa_average': 0.0,
        }
    )


def reverse_barbers_clients(apps, schema_editor):
    """Elimina los barberos y clientes creados si se revierte la migración"""
    User = apps.get_model('auth', 'User')
    User.objects.filter(
        username__in=['josequintero', 'danielperez', 'marcogomez', 'andreslopez', 'lauratorres']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_create_initial_users'),
        ('establishment', '0002_create_initial_establishments'),
    ]

    operations = [
        migrations.RunPython(create_barbers_and_clients, reverse_barbers_clients),
    ]
