# Generated by Django 5.2 on 2025-09-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_alter_profile_phone'),
        ('login_module', '0004_alter_profile_phone'),
    ]

    operations = [
    ]
