# Generated by Django 5.2 on 2025-09-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0005_merge_20250901_1849'),
        ('login_module', '0005_merge_20250905_2049'),
    ]

    operations = [
    ]
