# Generated by Django 5.2 on 2025-05-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('experiencia', models.PositiveIntegerField(blank=True, help_text='Años de experiencia', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguridadBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_seguridad', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_seguridad', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('nuevo_horario', models.TextField(blank=True, help_text='Formato sugerido: día: inicio-fin;...', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidades', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='barberos/')),
                ('establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento')),
            ],
        ),
    ]
