# Generated by Django 5.2.4 on 2025-07-05 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('permiso', 'Permiso Personal'), ('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad Médica'), ('licencia', 'Licencia (ej. luto u otras razones)')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_barbero', to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_barbero', to='admin_module.establishment')),
            ],
            options={
                'verbose_name': 'Solicitud de Barbero',
                'verbose_name_plural': 'Solicitudes de Barberos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
