# Generated by Django 5.2 on 2025-05-26 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber_module', '0001_initial'),
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_module.usuario'),
        ),
        migrations.AddField(
            model_name='horariobarbero',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber_module.barbero'),
        ),
        migrations.AddField(
            model_name='perfilbarbero',
            name='barbero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barber_module.barbero'),
        ),
        migrations.AddField(
            model_name='seguridadbarbero',
            name='barbero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barber_module.barbero'),
        ),
        migrations.AddField(
            model_name='solicitudcambiohorario',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber_module.barbero'),
        ),
    ]
