# Generated by Django 5.2 on 2025-10-07 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_module', '0001_initial'),
        ('establishment', '0002_create_initial_establishments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberrequest',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_barbero', to='establishment.establishment'),
        ),
    ]
