# Generated by Django 5.2 on 2025-05-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('password2', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
