# Generated by Django 5.2 on 2025-07-08 03:52

from django.db import migrations
from django.conf import settings

def create_initial_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    group_names = ['Administrador', 'Barbero', 'Cliente']

    for name in group_names:
        Group.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_initial_groups),
    ]
