# Generated by Django 5.2 on 2025-10-17 21:30

from django.db import migrations
from django.conf import settings


def create_initial_groups(apps, schema_editor):
    """
    Crea los grupos de usuarios iniciales necesarios para el sistema:
    - Administrador: Gestiona establecimientos
    - Barbero: Proporciona servicios
    - Cliente: Reserva servicios
    """
    Group = apps.get_model('auth', 'Group')

    group_names = ['Administrador', 'Barbero', 'Cliente']

    for name in group_names:
        Group.objects.get_or_create(name=name)


def reverse_groups(apps, schema_editor):
    """Elimina los grupos creados si se revierte la migración"""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Administrador', 'Barbero', 'Cliente']).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_initial_groups, reverse_groups),
    ]
