# Generated by Django 5.2 on 2025-11-10 00:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0002_create_initial_establishments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('category_type', models.CharField(choices=[('storable', 'Almacenable'), ('service', 'Servicio'), ('consumable', 'No Contable')], default='storable', max_length=20, verbose_name='Tipo de categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.productcategory', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('internal_reference', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Referencia interna')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('product_type', models.CharField(choices=[('simple', 'Producto Simple'), ('composite', 'Producto Compuesto')], default='simple', max_length=20, verbose_name='Tipo de producto')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de costo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de venta')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Controlar inventario')),
                ('minimum_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo')),
                ('maximum_stock', models.IntegerField(default=0, help_text='0 = sin límite máximo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock máximo')),
                ('unit_of_measure', models.CharField(default='unidad', help_text='ej: unidad, litro, metro, gramo', max_length=20, verbose_name='Unidad de medida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjustment_in', 'Ajuste Positivo'), ('adjustment_out', 'Ajuste Negativo'), ('transfer', 'Transferencia')], max_length=20, verbose_name='Tipo de movimiento')),
                ('reason', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('return', 'Devolución'), ('damaged', 'Producto dañado'), ('expired', 'Producto vencido'), ('inventory_adjustment', 'Ajuste de inventario'), ('initial_stock', 'Stock inicial'), ('production', 'Producción'), ('consumption', 'Consumo'), ('transfer', 'Transferencia'), ('other', 'Otro')], max_length=30, verbose_name='Motivo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo unitario')),
                ('reference', models.CharField(blank=True, help_text='Número de factura, orden, etc.', max_length=100, null=True, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='establishment.establishment', verbose_name='Establecimiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad necesaria')),
                ('unit_of_measure', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='product.product', verbose_name='Componente')),
                ('parent_product', models.ForeignKey(limit_choices_to={'product_type': 'composite'}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='product.product', verbose_name='Producto padre')),
            ],
            options={
                'verbose_name': 'Composición de Producto',
                'verbose_name_plural': 'Composiciones de Productos',
                'unique_together': {('parent_product', 'component_product')},
            },
        ),
        migrations.CreateModel(
            name='ProductEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Stock actual')),
                ('reserved_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Stock reservado')),
                ('location', models.CharField(blank=True, help_text='Estante, anaquel, etc.', max_length=100, null=True, verbose_name='Ubicación')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_stock', to='establishment.establishment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments_stock', to='product.product')),
            ],
            options={
                'verbose_name': 'Stock por Establecimiento',
                'verbose_name_plural': 'Stock por Establecimientos',
                'unique_together': {('product', 'establishment')},
            },
        ),
    ]
