# Generated by Django 5.2 on 2025-05-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        ('barber_module', '0001_initial'),
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber_module.barbero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_module.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCitasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.cita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_module.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencias', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_module.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_deseada', models.TimeField()),
                ('servicios_solicitados', models.TextField(help_text='Lista de IDs de servicios solicitados separados por coma')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_module.usuario')),
                ('establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento')),
            ],
        ),
    ]
