# Generated by Django 5.2 on 2025-12-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_create_default_categories'),
        ('services_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dates', to='product.productestablishment'),
        ),
    ]
