# Generated by Django 5.2 on 2025-07-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedate',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
