# Generated by Django 5.2 on 2025-12-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_create_initial_establishments'),
        ('product', '0002_create_default_categories'),
        ('services_module', '0002_alter_servicedate_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedate',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_dates', to='establishment.establishment'),
        ),
        migrations.AddField(
            model_name='servicedate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_dates', to='product.product'),
        ),
        migrations.AlterField(
            model_name='servicedate',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_dates_old', to='product.productestablishment'),
        ),
    ]
