# Generated by Django 5.2 on 2025-12-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_create_initial_establishments'),
        ('product', '0002_create_default_categories'),
        ('services_module', '0004_migrate_service_to_product_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedate',
            name='service',
        ),
        migrations.AlterField(
            model_name='servicedate',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dates', to='establishment.establishment'),
        ),
        migrations.AlterField(
            model_name='servicedate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dates', to='product.product'),
        ),
    ]
