# Generated by Django 5.2 on 2025-10-17 21:34

from django.db import migrations


def insert_initial_workflow_states(apps, schema_editor):
    """
    Crea los estados de flujo iniciales para el sistema de reservas.
    Estados disponibles:
    - Agendada: Cita programada
    - Confirmada: Cliente confirmó asistencia
    - En espera: Cliente esperando atención
    - Completada: Servicio finalizado
    - Cancelada: Cita cancelada
    - Reprogramada: Cita movida a otra fecha
    - No asistida: Cliente no se presentó
    """
    FlowStatus = apps.get_model('workflows', 'FlowStatus')

    initial_states = [
        ('Agendada', 'Solicitud programada en el calendario.'),
        ('Confirmada', 'Cliente confirmó su asistencia a la cita.'),
        ('En espera', 'Cliente en el establecimiento esperando atención.'),
        ('Completada', 'Servicio completado exitosamente.'),
        ('Cancelada', 'Cita cancelada por el cliente o barbero.'),
        ('Reprogramada', 'Cita movida a otra fecha u horario.'),
        ('No asistida', 'Cliente no se presentó a la cita.'),
    ]

    for name, description in initial_states:
        FlowStatus.objects.get_or_create(
            name=name,
            defaults={
                'description': description,
                'type_flow': None,
                'final': name in ['Completada', 'Cancelada', 'No asistida']
            }
        )


def reverse_workflow_states(apps, schema_editor):
    """Elimina los estados de flujo si se revierte la migración"""
    FlowStatus = apps.get_model('workflows', 'FlowStatus')
    FlowStatus.objects.filter(
        name__in=['Agendada', 'Confirmada', 'En espera', 'Completada', 
                  'Cancelada', 'Reprogramada', 'No asistida']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_workflow_states, reverse_workflow_states),
    ]
