# Generated by Django 5.2 on 2025-10-17 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_est', models.CharField(max_length=50)),
                ('address_est', models.CharField(max_length=80)),
                ('city_est', models.CharField(max_length=20)),
                ('country_est', models.CharField(max_length=20)),
                ('phone_est', models.CharField(max_length=20)),
                ('email_est', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('lat_est', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng_est', models.DecimalField(decimal_places=6, max_digits=9)),
                ('img_est', models.ImageField(blank=True, null=True, upload_to='establishments/')),
                ('qa_average_est', models.FloatField(default=5.0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_est', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'establishment',
            },
        ),
    ]
