# Generated by Django 5.2 on 2025-07-15 02:45

from django.db import migrations

def create_initial_establishments(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Establishment = apps.get_model('establishment', 'Establishment')

    
    # Obtener usuarios creados previamente (migración en login_module)
    try:
        admin1 = User.objects.get(username='admin1')
        admin2 = User.objects.get(username='admin2')
    except User.DoesNotExist:
        return  # Si no existen aún, abortar (o lanzar error si prefieres)

    # Crear establecimientos de prueba
    Establishment.objects.get_or_create(
        name_est='Establecimiento 1',
        defaults={
            'address_est': 'Calle Kennedy 123',
            'city_est': 'Bogotá',
            'country_est': 'Colombia',
            'phone_est': '3213245588',
            'email_est': 'Kennedy1@establecimiento1.com',
            'description': 'Barberia de confianza para ti y tu estilo.',
            'lat_est': 12.345678,
            'lng_est': 98.765432,
            'qa_average_est': 5.0,
            'active': True,
            'id_admin': admin1,
        }
    )

    Establishment.objects.get_or_create(
        name_est='Establecimiento 2',
        defaults={
            'address_est': 'Calle Timiza 123',
            'city_est': 'Bogotá',
            'country_est': 'Colombia',
            'phone_est': '3213245909',
            'email_est': 'Kennedy2@establecimiento1.com',
            'description': 'No encontraras un mejor lugar para sacar el maximo de ti.',
            'lat_est': 10.345678,
            'lng_est': 96.765432,
            'qa_average_est': 5.0,
            'active': True,
            'id_admin': admin2,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
        ('login_module', '0002_create_initial_users'),
    ]

    operations = [
        migrations.RunPython(create_initial_establishments)
    ]
