# Generated by Django 5.2 on 2025-10-17 21:32

from django.db import migrations


def create_initial_establishments(apps, schema_editor):
    """
    Crea establecimientos de prueba iniciales para demostración.
    Cada administrador gestiona un establecimiento.
    """
    User = apps.get_model('auth', 'User')
    Establishment = apps.get_model('establishment', 'Establishment')

    # Obtener usuarios administradores
    try:
        admin1 = User.objects.get(username='admin1')
        admin2 = User.objects.get(username='admin2')
    except User.DoesNotExist:
        return  # Si no existen los usuarios, no crear establecimientos

    # Establecimiento 1 - Kennedy
    Establishment.objects.get_or_create(
        name_est='BarberShop Kennedy',
        defaults={
            'address_est': 'Calle Kennedy 123 #45-67',
            'city_est': 'Bogotá',
            'country_est': 'Colombia',
            'phone_est': '3213245588',
            'email_est': 'kennedy@barberb.com',
            'description': 'Barbería moderna con los mejores servicios de la zona Kennedy.',
            'lat_est': 4.6097100,
            'lng_est': -74.0817500,
            'qa_average_est': 5.0,
            'active': True,
            'id_admin': admin1,
        }
    )

    # Establecimiento 2 - Timiza
    Establishment.objects.get_or_create(
        name_est='BarberShop Timiza',
        defaults={
            'address_est': 'Avenida Timiza 456 #78-90',
            'city_est': 'Bogotá',
            'country_est': 'Colombia',
            'phone_est': '3213245909',
            'email_est': 'timiza@barberb.com',
            'description': 'El mejor estilo para ti, calidad y profesionalismo.',
            'lat_est': 4.5850200,
            'lng_est': -74.1345600,
            'qa_average_est': 5.0,
            'active': True,
            'id_admin': admin2,
        }
    )


def reverse_establishments(apps, schema_editor):
    """Elimina los establecimientos creados si se revierte la migración"""
    Establishment = apps.get_model('establishment', 'Establishment')
    Establishment.objects.filter(
        name_est__in=['BarberShop Kennedy', 'BarberShop Timiza']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
        ('login_module', '0002_create_initial_users'),
    ]

    operations = [
        migrations.RunPython(create_initial_establishments, reverse_establishments),
    ]
