# Generated by Django 5.2 on 2025-05-29 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_est', models.CharField(max_length=50)),
                ('address_est', models.CharField(max_length=80)),
                ('city_est', models.CharField(max_length=20)),
                ('country_est', models.CharField(max_length=20)),
                ('phone_est', models.IntegerField()),
                ('email_est', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('lat_est', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng_est', models.DecimalField(decimal_places=6, max_digits=9)),
                ('img_est', models.ImageField(upload_to='establishments/')),
                ('qa_average_est', models.FloatField()),
                ('created_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=30)),
                ('description_product', models.CharField(max_length=80)),
                ('amount', models.IntegerField()),
                ('minimum_stock', models.IntegerField()),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=60)),
                ('description_service', models.CharField(max_length=100)),
                ('price_service', models.FloatField()),
                ('duration', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.establishment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.establishment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.service')),
            ],
        ),
    ]
