# Generated by Django 5.2 on 2025-10-07 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
        ('establishment', '0002_create_initial_establishments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentservice',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.establishment'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.establishment'),
        ),
        migrations.AlterModelTable(
            name='establishment',
            table='admin_module_establishment',
        ),
    ]
