# Generated by Django 5.2 on 2025-12-02 21:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
        ('establishment', '0002_create_initial_establishments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentSlotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_slot_duration', models.IntegerField(default=30, help_text='Duración por defecto de cada slot en minutos (15-120)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)])),
                ('buffer_time_between_appointments', models.IntegerField(default=5, help_text='Tiempo de descanso entre citas en minutos (0-30)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('advance_booking_days', models.IntegerField(default=30, help_text='Días de anticipación máxima para agendar citas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('min_advance_booking_hours', models.IntegerField(default=2, help_text='Horas mínimas de anticipación para agendar', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)])),
                ('allow_same_day_booking', models.BooleanField(default=True, help_text='¿Permitir reservas el mismo día?')),
                ('send_appointment_reminders', models.BooleanField(default=True, help_text='¿Enviar recordatorios de citas por email/SMS?')),
                ('reminder_hours_before', models.IntegerField(default=24, help_text='Horas antes de la cita para enviar recordatorio (1-168)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('send_confirmation_immediately', models.BooleanField(default=True, help_text='¿Enviar confirmación inmediata al agendar?')),
                ('allow_online_cancellation', models.BooleanField(default=True, help_text='¿Permitir cancelación online de citas?')),
                ('min_cancellation_hours', models.IntegerField(default=2, help_text='Horas mínimas antes de la cita para poder cancelar (0-48)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(48)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.OneToOneField(help_text='Establecimiento al que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='slot_config', to='establishment.establishment')),
            ],
            options={
                'verbose_name': 'Configuración de Slots',
                'verbose_name_plural': 'Configuraciones de Slots',
                'db_table': 'admin_module_establishmentslotconfiguration',
            },
        ),
        migrations.CreateModel(
            name='BarberAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('start_time', models.TimeField(help_text='Hora de inicio del turno')),
                ('end_time', models.TimeField(help_text='Hora de fin del turno')),
                ('is_available', models.BooleanField(default=True, help_text='¿El barbero trabaja este día?')),
                ('barber', models.ForeignKey(limit_choices_to={'groups__name': 'Barbero'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_availabilities', to='establishment.establishment')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Barbero',
                'verbose_name_plural': 'Disponibilidades de Barberos',
                'ordering': ['establishment', 'barber', 'day_of_week'],
                'unique_together': {('barber', 'establishment', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='EstablishmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('opening_time', models.TimeField(help_text='Hora de apertura (ej: 09:00)')),
                ('closing_time', models.TimeField(help_text='Hora de cierre (ej: 19:00)')),
                ('is_open', models.BooleanField(default=True, help_text='¿El local abre este día?')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='establishment.establishment')),
            ],
            options={
                'verbose_name': 'Horario de Establecimiento',
                'verbose_name_plural': 'Horarios de Establecimientos',
                'ordering': ['establishment', 'day_of_week'],
                'unique_together': {('establishment', 'day_of_week')},
            },
        ),
    ]
