# Generated by Django 5.2 on 2025-05-26 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0001_initial'),
        ('barber_module', '0001_initial'),
        ('login_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionestablecimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_module.usuario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='barbero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barber_module.barbero'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to='login_module.usuario'),
        ),
        migrations.AddField(
            model_name='citaservicio',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.cita'),
        ),
        migrations.AddField(
            model_name='configuracionestablecimiento',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento'),
        ),
        migrations.AddField(
            model_name='calificacionestablecimiento',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento'),
        ),
        migrations.AddField(
            model_name='horarioestablecimiento',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_module.establecimiento'),
        ),
        migrations.AddField(
            model_name='citaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.servicio'),
        ),
    ]
