# Generated by Django 5.2 on 2025-10-17 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
        ('establishment', '0002_create_initial_establishments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio de la ausencia')),
                ('end_date', models.DateField(help_text='Fecha de fin de la ausencia')),
                ('start_time', models.TimeField(blank=True, help_text='Hora de inicio (opcional, para ausencias parciales)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Hora de fin (opcional, para ausencias parciales)', null=True)),
                ('all_day', models.BooleanField(default=True, help_text='¿Es ausencia de todo el día?')),
                ('reason', models.CharField(help_text='Motivo de la ausencia (vacaciones, permiso médico, etc.)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(limit_choices_to={'groups__name': 'Barbero'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ausencia de Barbero',
                'verbose_name_plural': 'Ausencias de Barberos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BarberAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('start_time', models.TimeField(help_text='Hora de inicio del turno')),
                ('end_time', models.TimeField(help_text='Hora de fin del turno')),
                ('is_available', models.BooleanField(default=True, help_text='¿El barbero trabaja este día?')),
                ('barber', models.ForeignKey(limit_choices_to={'groups__name': 'Barbero'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_availabilities', to='establishment.establishment')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Barbero',
                'verbose_name_plural': 'Disponibilidades de Barberos',
                'ordering': ['establishment', 'barber', 'day_of_week'],
                'unique_together': {('barber', 'establishment', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='EstablishmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('opening_time', models.TimeField(help_text='Hora de apertura (ej: 09:00)')),
                ('closing_time', models.TimeField(help_text='Hora de cierre (ej: 19:00)')),
                ('is_open', models.BooleanField(default=True, help_text='¿El local abre este día?')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='establishment.establishment')),
            ],
            options={
                'verbose_name': 'Horario de Establecimiento',
                'verbose_name_plural': 'Horarios de Establecimientos',
                'ordering': ['establishment', 'day_of_week'],
                'unique_together': {('establishment', 'day_of_week')},
            },
        ),
    ]
