# Generated by Django 5.2.4 on 2025-07-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_service',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_module.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
