# Generated by Django 5.2 on 2025-07-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_remove_service_description_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='description_service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='name_service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='price_service',
        ),
    ]
