# Generated by Django 5.2.4 on 2025-07-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_rename_description_service_description_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
