# Generated by Django 5.2 on 2025-09-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_alter_category_name'),
        ('admin_module', '0007_create_initial_services'),
    ]

    operations = [
    ]
