# Generated by Django 5.2 on 2025-09-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0008_merge_20250901_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='img_est',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/'),
        ),
    ]
