# Generated by Django 5.2 on 2025-09-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0008_merge_20250901_1852'),
        ('admin_module', '0008_merge_20250905_2049'),
    ]

    operations = [
    ]
