"""
Django settings for barberb project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g+h5pxxd%f1f$!y7smq!gy%sj$r-f57_rg%p(#%x6_6e0us46w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Environment Variables with decouple
#DataBase Info
MAPS_APIKEY = config('MAPS_APIKEY')
DB_NAME = config('DB_NAME')
DB_USER = config('DB_USER')
DB_PASSW = config('DB_PASSW')
DB_HOST = config('DB_HOST')
DB_PORT = config('DB_PORT')

#Data of Sender Email
EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

#Data of Google Social Auth
CLIENT_ID_DE_GOOGLE = config('CLIENT_ID_DE_GOOGLE') 
CLIENT_SECRET_DE_GOOGLE = config('CLIENT_SECRET_DE_GOOGLE')

ALLOWED_HOSTS = [
    'barberb.online',
    'barberb-service-878619629488.us-central1.run.app',
    '127.0.0.1', 
    'localhost'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Sitios → usado para identificar el dominio actual (necesario para allauth)
    'django.contrib.sites',

    # django-allauth: manejo de cuentas y login social
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Proveedor Google

    # Apps del proyecto BarberB
    'core', 
    'admin_module',
    'services_module',
    'barber_module',
    'login_module',
    'widget_tweaks',
    'calendar_module',
    'workflows',
    'login_auth',
    'establishment',
    'notifications',
    ]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.CurrentRolMiddleware',
    'core.middleware.NoCacheMiddleware',  # Prevenir caché de páginas
    'core.middleware.SecurityHeadersMiddleware',  # Headers de seguridad adicionales
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'barberb.urls'

CSRF_TRUSTED_ORIGINS = [
    "https://barberb-service-878619629488.us-central1.run.app",
    "https://barberb.online"
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR / 'templates'],  # << Asegúrate que esté esto
        'APP_DIRS': True,
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Esto NO afecta la carga de templates de tus apps. APP_DIRS: True garantiza que Django siga buscando dentro de cada app también.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin_module.context_processors.solicitudes_pendientes', #funcionalidad para notificaciones de solicitudes barberos

            ],
        },
    },
]

WSGI_APPLICATION = 'barberb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

IS_CLOUD_RUN = os.getenv("K_SERVICE", None) is not None

if IS_CLOUD_RUN:
    # Configuración para Cloud SQL (usando socket de conexión)
    DB_NAME = os.getenv("DB_NAME")
    DB_USER = os.getenv("DB_USER")
    DB_PASSW = os.getenv("DB_PASSW")
    DB_PORT = os.getenv("DB_PORT", "3306")
    DB_CONNECTION_NAME = os.getenv("DB_CONNECTION_NAME")  # <-- lo inyectaremos

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "USER": DB_USER,
            "PASSWORD": DB_PASSW,
            "NAME": DB_NAME,
            "HOST": f"/cloudsql/{DB_CONNECTION_NAME}",
            "PORT": DB_PORT,
        }
    }
else:
    # Config local (usa los valores del .env)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSW"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT"),
        }
    }

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': CLIENT_ID_DE_GOOGLE,
            'secret': CLIENT_SECRET_DE_GOOGLE,
            'key': ''
        },
    "AUTH_PARAMS": {
            "prompt": "select_account"
        }
    }
}

#Envia directamente al proveedor de autenticación social, es decir nos envia en este caso a Google directamente
SOCIALACCOUNT_LOGIN_ON_GET = True


ACCOUNT_ADAPTER = "login_module.adapters.CustomAccountAdapter"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Necesario para django-allauth, identifica el "sitio" en el que corre la app
# Django utiliza esta referencia en la tabla django_site para saber si
# se está ejecutando en localhost o en un dominio en producción.
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # 1. Backend por defecto de Django (usuario + contraseña en BD local)
    'django.contrib.auth.backends.ModelBackend',

    # 2. Backend de django-allauth (permite autenticación social)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# URL de redirección después de un login exitoso
LOGIN_REDIRECT_URL = 'login_module:redirect_after_login'

# URL de redirección después de un logout
LOGOUT_REDIRECT_URL = 'login_module:login'

ACCOUNT_LOGOUT_REDIRECT_URL = LOGOUT_REDIRECT_URL


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login_module/login/'

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

# ============================================
# CONFIGURACIÓN DE EMAIL
# ============================================

# Para desarrollo: mostrar emails en consola (comentar para enviar emails reales)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Para producción: envío real de emails con Gmail/SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Variable de entorno
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # App password de Gmail

# URL base del sitio (para links en emails)
SITE_URL = 'http://localhost:8000'  # Cambiar en producción

# ============================================
# CONFIGURACIONES DE SEGURIDAD ADICIONALES
# ============================================

# Configuración de sesiones
SESSION_COOKIE_HTTPONLY = True  # Prevenir acceso a cookies via JavaScript
SESSION_COOKIE_SECURE = not DEBUG  # Solo HTTPS en producción
SESSION_COOKIE_SAMESITE = 'Lax'  # Prevenir CSRF
SESSION_COOKIE_AGE = 3600  # Sesión expira en 1 hora (3600 segundos)
SESSION_SAVE_EVERY_REQUEST = True  # Actualizar la expiración en cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Cerrar sesión al cerrar navegador

# Configuración de CSRF
CSRF_COOKIE_HTTPONLY = True  # Prevenir acceso a cookie CSRF via JavaScript
CSRF_COOKIE_SECURE = not DEBUG  # Solo HTTPS en producción
CSRF_COOKIE_SAMESITE = 'Lax'  # Prevenir ataques CSRF

# Seguridad para producción
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Redirigir HTTP a HTTPS
    SECURE_HSTS_SECONDS = 31536000  # HSTS por 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Configuración de Password
PASSWORD_RESET_TIMEOUT = 3600  # Link de reset expira en 1 hora

